In [1]:
import numpy as np
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [2]:
arr1= np.array([84,58,96,36])

In [3]:
arr1.ndim

1

In [4]:
arr1.shape

(4,)

In [5]:
arr1.dtype

dtype('int32')

In [6]:
arr2 = np.array([[87,45,78,50],[45,78,96,35]],dtype=int)
arr2

array([[87, 45, 78, 50],
       [45, 78, 96, 35]])

In [7]:
arr2.shape

(2, 4)

In [8]:
arr2.ndim

2

In [9]:
np.linspace(14,50)

array([14.        , 14.73469388, 15.46938776, 16.20408163, 16.93877551,
       17.67346939, 18.40816327, 19.14285714, 19.87755102, 20.6122449 ,
       21.34693878, 22.08163265, 22.81632653, 23.55102041, 24.28571429,
       25.02040816, 25.75510204, 26.48979592, 27.2244898 , 27.95918367,
       28.69387755, 29.42857143, 30.16326531, 30.89795918, 31.63265306,
       32.36734694, 33.10204082, 33.83673469, 34.57142857, 35.30612245,
       36.04081633, 36.7755102 , 37.51020408, 38.24489796, 38.97959184,
       39.71428571, 40.44897959, 41.18367347, 41.91836735, 42.65306122,
       43.3877551 , 44.12244898, 44.85714286, 45.59183673, 46.32653061,
       47.06122449, 47.79591837, 48.53061224, 49.26530612, 50.        ])

In [11]:
np.linspace(14,50,20)

array([14.        , 15.89473684, 17.78947368, 19.68421053, 21.57894737,
       23.47368421, 25.36842105, 27.26315789, 29.15789474, 31.05263158,
       32.94736842, 34.84210526, 36.73684211, 38.63157895, 40.52631579,
       42.42105263, 44.31578947, 46.21052632, 48.10526316, 50.        ])

In [12]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones(15) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [16]:
np.zeros(15) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [17]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [21]:
arr3 = np. arange(1,101)
arr3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101])

In [22]:
arr3 = np. arange(1,101,3)
arr3

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [23]:
arr4 = np.random.randint(15,100)
arr4

95

In [34]:
np.random.seed(1)
arr4 = np.random.randint(15,100,100)
arr4

array([52, 27, 87, 24, 90, 20, 94, 79, 31, 16, 91, 86, 21, 40, 65, 35, 33,
       99, 26, 43, 44, 29, 65, 83, 28, 24, 22, 78, 76, 37, 72, 16, 15, 75,
       96, 23, 28, 62, 87, 45, 86, 18, 85, 36, 64, 72, 18, 83, 39, 58, 91,
       41, 67, 95, 56, 97, 30, 79, 83, 40, 22, 41, 40, 37, 24, 82, 38, 42,
       52, 72, 98, 53, 23, 47, 49, 25, 38, 30, 40, 86, 89, 77, 61, 47, 38,
       70, 80, 92, 18, 15, 92, 21, 67, 85, 17, 91, 36, 90, 22, 92])

In [35]:
arr4 =arr4.reshape(10,10)
arr4

array([[52, 27, 87, 24, 90, 20, 94, 79, 31, 16],
       [91, 86, 21, 40, 65, 35, 33, 99, 26, 43],
       [44, 29, 65, 83, 28, 24, 22, 78, 76, 37],
       [72, 16, 15, 75, 96, 23, 28, 62, 87, 45],
       [86, 18, 85, 36, 64, 72, 18, 83, 39, 58],
       [91, 41, 67, 95, 56, 97, 30, 79, 83, 40],
       [22, 41, 40, 37, 24, 82, 38, 42, 52, 72],
       [98, 53, 23, 47, 49, 25, 38, 30, 40, 86],
       [89, 77, 61, 47, 38, 70, 80, 92, 18, 15],
       [92, 21, 67, 85, 17, 91, 36, 90, 22, 92]])

In [36]:
arr4 [2:7,3:7]=50
arr4

array([[52, 27, 87, 24, 90, 20, 94, 79, 31, 16],
       [91, 86, 21, 40, 65, 35, 33, 99, 26, 43],
       [44, 29, 65, 50, 50, 50, 50, 78, 76, 37],
       [72, 16, 15, 50, 50, 50, 50, 62, 87, 45],
       [86, 18, 85, 50, 50, 50, 50, 83, 39, 58],
       [91, 41, 67, 50, 50, 50, 50, 79, 83, 40],
       [22, 41, 40, 50, 50, 50, 50, 42, 52, 72],
       [98, 53, 23, 47, 49, 25, 38, 30, 40, 86],
       [89, 77, 61, 47, 38, 70, 80, 92, 18, 15],
       [92, 21, 67, 85, 17, 91, 36, 90, 22, 92]])

In [37]:
arr4[4,4]

50

In [38]:
arr4 = arr4.flatten()
arr4

array([52, 27, 87, 24, 90, 20, 94, 79, 31, 16, 91, 86, 21, 40, 65, 35, 33,
       99, 26, 43, 44, 29, 65, 50, 50, 50, 50, 78, 76, 37, 72, 16, 15, 50,
       50, 50, 50, 62, 87, 45, 86, 18, 85, 50, 50, 50, 50, 83, 39, 58, 91,
       41, 67, 50, 50, 50, 50, 79, 83, 40, 22, 41, 40, 50, 50, 50, 50, 42,
       52, 72, 98, 53, 23, 47, 49, 25, 38, 30, 40, 86, 89, 77, 61, 47, 38,
       70, 80, 92, 18, 15, 92, 21, 67, 85, 17, 91, 36, 90, 22, 92])

In [40]:
arr4[arr4 >=45]

array([52, 87, 90, 94, 79, 91, 86, 65, 99, 65, 50, 50, 50, 50, 78, 76, 72,
       50, 50, 50, 50, 62, 87, 45, 86, 85, 50, 50, 50, 50, 83, 58, 91, 67,
       50, 50, 50, 50, 79, 83, 50, 50, 50, 50, 52, 72, 98, 53, 47, 49, 86,
       89, 77, 61, 47, 70, 80, 92, 92, 67, 85, 91, 90, 92])

In [41]:
arr4[arr4 ==45]

array([45])

In [42]:
arr4[arr4 !=45]

array([52, 27, 87, 24, 90, 20, 94, 79, 31, 16, 91, 86, 21, 40, 65, 35, 33,
       99, 26, 43, 44, 29, 65, 50, 50, 50, 50, 78, 76, 37, 72, 16, 15, 50,
       50, 50, 50, 62, 87, 86, 18, 85, 50, 50, 50, 50, 83, 39, 58, 91, 41,
       67, 50, 50, 50, 50, 79, 83, 40, 22, 41, 40, 50, 50, 50, 50, 42, 52,
       72, 98, 53, 23, 47, 49, 25, 38, 30, 40, 86, 89, 77, 61, 47, 38, 70,
       80, 92, 18, 15, 92, 21, 67, 85, 17, 91, 36, 90, 22, 92])

In [43]:
arr4[arr4 < 45]

array([27, 24, 20, 31, 16, 21, 40, 35, 33, 26, 43, 44, 29, 37, 16, 15, 18,
       39, 41, 40, 22, 41, 40, 42, 23, 25, 38, 30, 40, 38, 18, 15, 21, 17,
       36, 22])

In [44]:
np.mean(arr4)

54.13

In [45]:
np.median(arr4)

50.0

In [46]:
np.sum(arr4)

5413

In [47]:
np.min(arr4)

15

In [48]:
np.max(arr4)

99

In [49]:
np.argmax(arr4)

17

In [50]:
np.std(arr4)

23.913868361266857

In [51]:
np.var(arr4)

571.8731

In [52]:
np.cos(arr4)

array([-0.16299078, -0.29213881,  0.56975033,  0.42417901, -0.44807362,
        0.40808206,  0.96945937, -0.89597095,  0.91474236, -0.95765948,
       -0.99436746, -0.38369844, -0.54772926, -0.66693806, -0.56245385,
       -0.90369221, -0.01327675,  0.03982088,  0.64691932,  0.5551133 ,
        0.99984331, -0.74805753, -0.56245385,  0.96496603,  0.96496603,
        0.96496603,  0.96496603, -0.85780309,  0.82433133,  0.76541405,
       -0.96725059, -0.95765948, -0.75968791,  0.96496603,  0.96496603,
        0.96496603,  0.96496603,  0.67350716,  0.56975033,  0.52532199,
       -0.38369844,  0.66031671, -0.98437664,  0.96496603,  0.96496603,
        0.96496603,  0.96496603,  0.24954012,  0.26664293,  0.11918014,
       -0.99436746, -0.98733928, -0.5177698 ,  0.96496603,  0.96496603,
        0.96496603,  0.96496603, -0.89597095,  0.24954012, -0.66693806,
       -0.99996083, -0.98733928, -0.66693806,  0.96496603,  0.96496603,
        0.96496603,  0.96496603, -0.39998531, -0.16299078, -0.96

In [53]:
np.argmax(arr4)

17

In [54]:
np.argmin(arr4)

32

In [55]:
np.percentile(arr4,78)

79.22

In [56]:
np.sqrt(arr4)

array([7.21110255, 5.19615242, 9.32737905, 4.89897949, 9.48683298,
       4.47213595, 9.69535971, 8.88819442, 5.56776436, 4.        ,
       9.53939201, 9.2736185 , 4.58257569, 6.32455532, 8.06225775,
       5.91607978, 5.74456265, 9.94987437, 5.09901951, 6.55743852,
       6.63324958, 5.38516481, 8.06225775, 7.07106781, 7.07106781,
       7.07106781, 7.07106781, 8.83176087, 8.71779789, 6.08276253,
       8.48528137, 4.        , 3.87298335, 7.07106781, 7.07106781,
       7.07106781, 7.07106781, 7.87400787, 9.32737905, 6.70820393,
       9.2736185 , 4.24264069, 9.21954446, 7.07106781, 7.07106781,
       7.07106781, 7.07106781, 9.11043358, 6.244998  , 7.61577311,
       9.53939201, 6.40312424, 8.18535277, 7.07106781, 7.07106781,
       7.07106781, 7.07106781, 8.88819442, 9.11043358, 6.32455532,
       4.69041576, 6.40312424, 6.32455532, 7.07106781, 7.07106781,
       7.07106781, 7.07106781, 6.4807407 , 7.21110255, 8.48528137,
       9.89949494, 7.28010989, 4.79583152, 6.8556546 , 7.     

# Exercise
# GENERATE AN ARRAY CONSISTING OF 120 VALUES USING SEED NUMBER 5
# RESHAPE THE ARRAY TO 2D OF 12 ROWS AND 10 COLUMNS
# SELECT THE VALUES FROM 5 TO 8 ON THE ROW AND 4 TO 6 ON THE COLUMN
# BROADCAST 32 ALL OVER THE SELECTED VALUE
# FIND THE MEAN, MEDIAN,(25,75,85 PERCENTILE)

In [61]:
arr5 = np. arange(1,121)
arr5

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120])

In [62]:
np.random.seed(1)
arr5 = np.random.randint(45,124,120)
arr5

array([ 82,  57, 117,  54, 120,  50, 109,  61,  46, 121, 116,  51,  70,
        95,  65,  63,  56,  73,  74,  59,  95, 113,  58,  54,  52, 108,
       106,  67, 102,  46,  45, 105,  53,  58,  92, 117,  75, 116,  48,
       115,  66,  94, 102,  48, 113,  69,  88, 121,  71,  97,  86,  60,
       109, 113,  70,  52,  71,  70,  67,  54, 112,  68,  72,  82, 102,
        83,  53,  77,  79,  55,  68,  60,  70, 116, 119, 107,  91,  77,
        68, 100, 110, 122,  48,  45, 122,  51,  97, 115,  47, 121,  66,
       120,  52, 122, 117, 120, 121,  88,  65,  75,  81,  52,  90, 113,
       102,  58,  55,  68,  52,  69, 119,  65,  77,  57, 110, 105,  69,
        47,  55,  99])

In [64]:
arr5 =arr5.reshape(10,12)
arr5

array([[ 82,  57, 117,  54, 120,  50, 109,  61,  46, 121, 116,  51],
       [ 70,  95,  65,  63,  56,  73,  74,  59,  95, 113,  58,  54],
       [ 52, 108, 106,  67, 102,  46,  45, 105,  53,  58,  92, 117],
       [ 75, 116,  48, 115,  66,  94, 102,  48, 113,  69,  88, 121],
       [ 71,  97,  86,  60, 109, 113,  70,  52,  71,  70,  67,  54],
       [112,  68,  72,  82, 102,  83,  53,  77,  79,  55,  68,  60],
       [ 70, 116, 119, 107,  91,  77,  68, 100, 110, 122,  48,  45],
       [122,  51,  97, 115,  47, 121,  66, 120,  52, 122, 117, 120],
       [121,  88,  65,  75,  81,  52,  90, 113, 102,  58,  55,  68],
       [ 52,  69, 119,  65,  77,  57, 110, 105,  69,  47,  55,  99]])

In [65]:
arr5 [5:8,4:6]
arr5

array([[ 82,  57, 117,  54, 120,  50, 109,  61,  46, 121, 116,  51],
       [ 70,  95,  65,  63,  56,  73,  74,  59,  95, 113,  58,  54],
       [ 52, 108, 106,  67, 102,  46,  45, 105,  53,  58,  92, 117],
       [ 75, 116,  48, 115,  66,  94, 102,  48, 113,  69,  88, 121],
       [ 71,  97,  86,  60, 109, 113,  70,  52,  71,  70,  67,  54],
       [112,  68,  72,  82, 102,  83,  53,  77,  79,  55,  68,  60],
       [ 70, 116, 119, 107,  91,  77,  68, 100, 110, 122,  48,  45],
       [122,  51,  97, 115,  47, 121,  66, 120,  52, 122, 117, 120],
       [121,  88,  65,  75,  81,  52,  90, 113, 102,  58,  55,  68],
       [ 52,  69, 119,  65,  77,  57, 110, 105,  69,  47,  55,  99]])

In [66]:
arr5 [5:8,4:6]=32
arr5

array([[ 82,  57, 117,  54, 120,  50, 109,  61,  46, 121, 116,  51],
       [ 70,  95,  65,  63,  56,  73,  74,  59,  95, 113,  58,  54],
       [ 52, 108, 106,  67, 102,  46,  45, 105,  53,  58,  92, 117],
       [ 75, 116,  48, 115,  66,  94, 102,  48, 113,  69,  88, 121],
       [ 71,  97,  86,  60, 109, 113,  70,  52,  71,  70,  67,  54],
       [112,  68,  72,  82,  32,  32,  53,  77,  79,  55,  68,  60],
       [ 70, 116, 119, 107,  32,  32,  68, 100, 110, 122,  48,  45],
       [122,  51,  97, 115,  32,  32,  66, 120,  52, 122, 117, 120],
       [121,  88,  65,  75,  81,  52,  90, 113, 102,  58,  55,  68],
       [ 52,  69, 119,  65,  77,  57, 110, 105,  69,  47,  55,  99]])

In [67]:
np.mean(25)

25.0

In [68]:
np.median(75)

75.0

In [71]:
np.percentile(arr5,25)

55.75

In [72]:
np.percentile(arr5,75)

106.25

In [73]:
np.percentile(arr5,85)

115.0